concertReview/config/routes.rb
ConcertReview::Application.routes.draw do
  resources :concerts, except: [:new, :edit, :delete]
  resources :artists, except: [:new, :edit, :delete]
  resources :reviews, except: [:edit, :delete]

  get "sessions/new"
  get "users/new"  
  resources :users
  resources :sessions

  get "review/index"
  get "review/artist"
  get "review/date"
  get "review/venue"
  get "review/genre"
  get "review/comments"

  root 'reviews#home'

  get 'reviews/' => 'reviews#home'
  get 'concerts/' => 'concert#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "account" => "sessions#account", :as => "account"
  

end

concertReview/app/models/artist.rb
require 'songkickr'
class Artist < ActiveRecord::Base
	extend FriendlyId

	friendly_id :name
	validates_presence_of :name
	has_many :concerts

	paginates_per 15


	def upcomingEvents

		@remote = Songkickr::Remote.new 'WrlX22JJAxW2489I'

		artistId = @remote.artist_search(self.name).results.first

		getId = artistId.id if !artistId.to_s.empty?
		
		if(getId != nil)
			artistConcerts = @remote.artist_events(getId, :per_page => '10').results
		end

		return artistConcerts
	end

	def self.search(query)
  		where("name like ?", "%#{query}%") 
	end

	def avgOverall
		avg = 0
		self.concerts.each do |concert|
			avg = avg + concert.averageOverall
		end
		return (avg/concerts.size*100).round / 100.0
	end

	def avgSound
		avg = 0
		self.concerts.each do |concert|
			avg = avg + concert.averageSound
		end
		return (avg/concerts.size*100).round / 100.0
	end

	def avgStagePresence
		avg = 0
		self.concerts.each do |concert|
			avg = avg + concert.averageStagePresence
		end
		return (avg/concerts.size*100).round / 100.0
	end

	def avgSongSelection
		avg = 0
		self.concerts.each do |concert|
			avg = avg + concert.averageSongSelection
		end
		return (avg/concerts.size*100).round / 100.0
	end

	def numReviews
		artistReviews = 0
		self.concerts.each do |concert|
			artistReviews += concert.reviews.size
		end
		return artistReviews
	end

end

concertReview/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

	def new
    	@artist = Artist.new
 	end
  # GET /artists
  # GET /artists.json
  def index
    if params[:search]
        @artists = Artist.search(params[:search].titleize).order("created_at DESC").page(params[:page])
    elsif params[:sort] == "numConcerts"
        @artists = Kaminari.paginate_array(Artist.all.sort_by{|artist| artist.concerts.size}.reverse).page(params[:page]).per(15)
    elsif params[:sort] == "avgRating"
        @artists = Kaminari.paginate_array(Artist.all.sort_by{|artist| artist.avgOverall}.reverse).page(params[:page]).per(15)
    elsif params[:sort] == "numReviews"
        @artists = Kaminari.paginate_array(Artist.all.sort_by{|artist| artist.numReviews}.reverse).page(params[:page]).per(15)
    else
        @artists = Artist.order(:name).page(params[:page])
    end
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @artist }
      else
        format.html { render action: 'new' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name)
    end
end

concertReview/app/helpers/artists_helper.rb
module ArtistsHelper
end

concertReview/app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

concertReview/app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

concertReview/app/views/artists/index.html.erb
<html>

<body>


  <div class="container">


    <div class="row">


        <div class="col-md-4">

        <div style=" border: 3px solid #FAF4F4;background: lightgrey; height: 500px" class="jumbotron">
         
                 <h2  style="color: grey;font-size: 30px; font-family: 'Oswald', sans-serif">  What do you say? </h2>


            <div style="border: 3px solid #FAF4F4"class="list-group">
              
              <a  style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Check out Artists</a>
              <a style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Write your Review!</a>
              <a style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Follow Your Band!</a>
              <a style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Upcoming Concerts</a>
            </div>
                
          </div>
      </div>

    

    
      <div class="col-md-8">

      <div style="border: 3px solid #FAF4F4;background: grey; height: 500px" class="jumbotron">

               <h2  style="color: white;font-size: 30px; font-family: 'Oswald', sans-serif">  Recent Concerts </h2>

    

         <div id = 'artists'>
            <% @artists.each do |artist| %>
                <div style="border:1px solid black; border-radius: 5px";>
                  <p><b><%= link_to artist.name, artist %></b> 
                  <% if artist.concerts.size > 1 %>
                    <%= " #{artist.concerts.size} concerts with " %> 
                  <% else %> 
                    <%= " #{artist.concerts.size} concert with " %> 
                  <% end %>

                  <% if artist.numReviews > 1 %>
                    <%= "#{artist.numReviews} reviews" %></p>
                  <% else %>
                    <%= "#{artist.numReviews} review" %></p>
                  <% end %>

                  <p>Average Overall Rating: <%= artist.avgOverall %></p>

                </div>

              <% end %>
         </div>
      </div>
    </div>

 


  <!-- end row -->
</div>
  <!-- end container -->
</div>

<%= paginate @artists %>


</body>
</html>





<!--
 <div>
        <%= form_tag(artists_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Artists" %>
          <%= submit_tag "Search", :name => nil %>
        <% end %>
        <br>

      </div>


      <div class = "col-12 col-md-3">
        <p><b>Sort </b> <%= link_to "Alphabetically", artists_path %></p>
      </div>


      <div class = "col-12 col-md-3">  
        <p><%= link_to "Average rating", :sort => "avgRating" %></p>
      </div>

      <div class = "col-12 col-md-4">
        <p><%= link_to "Number of Concerts  ", :sort => "numConcerts" %> //
           <%= link_to "Reviews" , :sort => "numReviews" %></p>
      </div>


-->

concertReview/app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

concertReview/app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>


<div class = "row">

	<div class = "col-12 col-md-9">
		<p><strong>Name: </strong><%= @artist.name %></p>

		<p><b>Average Ratings</b></p>
		<p>Overall: </b><%= @artist.avgOverall %></p>
		<p>Sound: </b><%= @artist.avgSound %></p>	
		<p>Song Selection: </b><%= @artist.avgSongSelection %></p>
		<p>Stage Presence: </b><%= @artist.avgStagePresence %></p>		

		<div style="border:1px solid black; border-radius: 5px";>

			<p><%= "#{@artist.concerts.size} concerts" %></p>
			<% @artist.concerts.each do |concert| %>
				<p><%= link_to concert.venue + " on "+ concert.date.to_s, concert %></p>
			<% end %>

		</div>

	</div>


<!--this should be on upper right corner of page probably -->

	<div class = "col-12 col-md-3">

		<p><strong>Upcoming Shows For <%= @artist.name%></strong></p>	

		<% if @artist.upcomingEvents != nil %>
		<% @artist.upcomingEvents.each do |event| %>
  			<p><%= link_to event.display_name + " " + event.location.city, event.uri, :target => "_blank"%></p>

		<% end %>

		<% else %>
			<p>None to display at this time</p>
		<% end %>

	</div>

</div>

<%= link_to 'Back', artists_path %>