concertReview/config/routes.rb
ConcertReview::Application.routes.draw do
  resources :concerts, except: [:new, :edit, :delete]
  resources :artists, except: [:new, :edit, :delete]
  resources :reviews, except: [:edit, :delete]

  get "sessions/new"
  get "users/new"  
  resources :users
  resources :sessions

  get "review/index"
  get "review/artist"
  get "review/date"
  get "review/venue"
  get "review/genre"
  get "review/comments"

  root 'reviews#home'

  get 'reviews/' => 'reviews#home'
  get 'concerts/' => 'concert#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "account" => "sessions#account", :as => "account"
  

end

concertReview/app/models/concert.rb
class Concert < ActiveRecord::Base
	validates_presence_of :venue
	validates_presence_of :date

	has_many :reviews
	belongs_to :artist

	paginates_per 15

	#dry these up into 1 function and use class variables? tried a few different things but didn't work
	def averageOverall
		avgOR = 0
		self.reviews.each do |review|
			avgOR = avgOR + review.overallRating
		end
		#not sure if should keep as int or a float, it rounds down at the moment .to_f for float
		return (avgOR.to_f/reviews.size*100).round / 100.0
	end

	def averageSound
		avgSound = 0
		self.reviews.each do |review|
			avgSound += review.sound
		end
		return (avgSound.to_f/reviews.size*100).round / 100.0
	end

	def averageStagePresence
		avgSP = 0
		self.reviews.each do |review|
			avgSP += review.stagePresence
		end
		return (avgSP.to_f/reviews.size*100).round / 100.0
	end

	def averageSongSelection
		avgSS = 0
		self.reviews.each do |review|
			avgSS += review.songSelection
		end
		return (avgSS.to_f/reviews.size*100).round / 100.0
	end
end

concertReview/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]
  helper_method :popularConcerts
  # GET /concerts
  # GET /concerts.json
  def index
    if params[:sort] == "numReviews"
      if params[:direction] == "asc"
        @concerts = Kaminari.paginate_array(Concert.all.sort_by{|concert| concert.reviews.size}.reverse).page(params[:page]).per(15)
      else
        @concerts = Kaminari.paginate_array(Concert.all.sort_by{|concert| concert.reviews.size}).page(params[:page]).per(15)
      end
    elsif params[:sort] == "artist"
      if params[:direction] == "asc"
        @concerts = Kaminari.paginate_array(Concert.all.sort_by{|concert| concert.artist.name}).page(params[:page]).per(15)
      else 
        @concerts = Kaminari.paginate_array(Concert.all.sort_by{|concert| concert.artist.name}.reverse).page(params[:page]).per(15)
      end
    elsif params[:sort] == "avgRating"
      if params[:direction] == "asc"
        @concerts = Kaminari.paginate_array(Concert.all.sort_by{|concert| concert.averageOverall}.reverse).page(params[:page]).per(15)
      else
        @concerts = Kaminari.paginate_array(Concert.all.sort_by{|concert| concert.averageOverall}).page(params[:page]).per(15)
      end
    elsif params[:sort] == "venue"
      @concerts = Concert.all.order(params[:sort]  + " " + params[:direction]).page(params[:page]).per(15)
    elsif params[:sort] == "date"
      @concerts = Concert.all.order(params[:sort] + " " + params[:direction]).page(params[:page]).per(15) 
    else  
      @concerts = Concert.all.page(params[:page])
    end
  end

  def popularConcerts
    @popularConcerts = Concert.all.sort_by{|concert| concert.reviews.size}.reverse.last(5)
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render action: 'show', status: :created, location: @concert }
      else
        format.html { render action: 'new' }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:venue, :date)
    end
end

concertReview/app/helpers/concert_helper.rb
module ConcertHelper
end

concertReview/app/helpers/concerts_helper.rb
module ConcertsHelper
end

concertReview/app/views/concerts/_form.html.erb
<%= form_for(@concert) do |f| %>
  <% if @concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% @concert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

concertReview/app/views/concerts/edit.html.erb
<h1>Editing concert</h1>

<%= render 'form' %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

concertReview/app/views/concerts/index.html.erb
<html>

<body>



<div class="container">



	<div style="background: #999; border: grey"class="panel panel-default">
       <div class="panel-body">
          <h2   align="center" style="font-size: 40px; color: white; margin-top: -4px; margin-bottom: -4px; font-family: 'Oswald', sans-serif">  Concerts </h2>
       </div>
    </div>


	<div class="row">


		<div class="col-md-4">

			<div style=" border: 3px solid #FAF4F4;background: lightgrey; height: 500px" class="jumbotron">
			 
		           <h2  style="color: grey;font-size: 30px; font-family: 'Oswald', sans-serif">  What do you say? </h2>


					<div style="border: 3px solid #FAF4F4"class="list-group">
					  
					  <a  style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Check out Artists</a>
					  <a style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Write your Review!</a>
					  <a style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Follow Your Band!</a>
					  <a style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Upcoming Concerts</a>
					</div>
		          
		    </div>
		</div>


		<div class="col-md-8">

			<div style="border: 3px solid #FAF4F4;background: grey; height: 500px" class="jumbotron">

               <h2  style="color: white;font-size: 30px; font-family: 'Oswald', sans-serif">  Recent Concerts </h2>

			  <table style="border: 3px solid #FAF4F4"class = "table">
			
			<tr>
				<th><%= sortable "artist", "Artist" %></th>
				<th><%= sortable "venue", "Venue" %></th>
				<th><%= sortable "date", "Date" %></th>
				<th><%= sortable "numReviews", "Reviews" %></th>
				<th><%= sortable "avgRating", "Average Overall Rating" %></th>
				<th>All Reviews & Ratings</th>
			</tr>

			<% @concerts.each do |concert| %>

			<tr>
				<td><%= link_to "#{concert.artist.name}", concert.artist %></td>
				<td><%= "#{concert.venue}" %></td>
				<td><%= "#{concert.date}" %></td>
				<td><%= "#{concert.reviews.size}" %></td>
				<td><%= "#{concert.averageOverall}" %></td>
				<td><%= link_to "Read More", concert %></td>
			</tr>

			<% end %>

			</table>

			    </div>
			</div>

	   </div>



			   <div style="background: #999; border: grey"class="panel panel-default">
		       <div class="panel-body">
		          <h2   align="center" style="font-size: 40px; color: white; margin-top: -4px; margin-bottom: -4px; font-family: 'Oswald', sans-serif">  Trending </h2>
		       </div>
		     </div>



				<div class="row">
				  <div class="col-sm-6 col-md-4">
				    <div class="thumbnail">
				      <img src="http://placehold.it/300x200" alt="...">
				      <div class="caption">
				       <h1>Rock in Rion</h1>                       
        				       
				      </div>
				    </div>
				  </div>


				  <div class="col-sm-6 col-md-4">
				    <div class="thumbnail">
				      <img src="http://placehold.it/300x200" alt="...">
				      <div class="caption">
				        <h1>OutsideLands</h1>                        
				       
				      </div>
				    </div>
				  </div>

				  <div class="col-sm-6 col-md-4">
				    <div class="thumbnail">
				      <img src="http://placehold.it/300x200" alt="...">
				      <div class="caption">
				        <h1>Coachella</h1>                        
				        
				      </div>
				    </div>
				  </div>

				  <div class="col-sm-6 col-md-4">
				    <div class="thumbnail">
				      <img src="http://placehold.it/300x200" alt="...">
				      <div class="caption">
				        <h1>REggaeontheRiver</h1>                        
				        
				      </div>
				    </div>
				  </div>

				  <div class="col-sm-6 col-md-4">
				    <div class="thumbnail">
				      <img src="http://placehold.it/300x200" alt="...">
				      <div class="caption">
				        <h1>Street Scene</h1>                        
				        
				      </div>
				    </div>
				  </div>

				  <div class="col-sm-6 col-md-4">
				    <div class="thumbnail">
				      <img src="http://placehold.it/300x200" alt="...">
				      <div class="caption">
				        <h1>Not so silent</h1>
                        
				        
				      </div>
				    </div>
				  </div>



				</div>















				<div class="row">


							
					<div class = "table-responsive">

						

					</div>


			    </div>




		</div>
	</div>


</body>
</html>




<!-- 
<div id = 'concerts' >
<% @concerts.each do |concert| %>
  <p><b><%= link_to "#{concert.artist.name} live at #{concert.venue} on #{concert.date}", concert %><%= " : #{concert.reviews.size} reviews" %></b></p>
<% end %>


<%= paginate @concerts %>



				<th>All Reviews & Ratings</th>
			</tr>

			  <% @concerts.each do |concert| %>

			<tr>
				<td><%= link_to "#{concert.artist.name}", concert.artist %></td>
				<td><%= "#{concert.venue}" %></td>
				<td><%= "#{concert.date}" %></td>
				<td><%= "#{concert.reviews.size}" %></td>
				<td><%= "#{concert.averageOverall}" %></td>
				<td><%= link_to "Read More", concert %></td>
			</tr>

			<% end %>

</div>



<table class = "table">
			
			<tr>
				<th><%= sortable "artist", "Artist" %></th>
				<th><%= sortable "venue", "Venue" %></th>
				<th><%= sortable "date", "Date" %></th>
				<th><%= sortable "numReviews", "Reviews" %></th>
				<th><%= sortable "avgRating", "Average Overall Rating" %></th>
				<th>All Reviews & Ratings</th>
			</tr>

			<% @concerts.each do |concert| %>

			<tr>
				<td><%= link_to "#{concert.artist.name}", concert.artist %></td>
				<td><%= "#{concert.venue}" %></td>
				<td><%= "#{concert.date}" %></td>
				<td><%= "#{concert.reviews.size}" %></td>
				<td><%= "#{concert.averageOverall}" %></td>
				<td><%= link_to "Read More", concert %></td>
			</tr>

			<% end %>

			</table>

-->

concertReview/app/views/concerts/new.html.erb
<!-- concert new view -->

<div class="container">


  <div style="background-color: white" class="container">


    <h1 style="font-family: sans-serif;
    color: grey;"> New Concert? </h1>





    <div class="row">



    <div class="col-md-4">

      <div style="color: grey;background: lightgrey; height: 550px" class="jumbotron">

      <table style="border: 3px solid #FAF4F4"class = "table">


      <p>
        <strong>Tell us what Concert</strong>

        
      </p>
    </table>


   

    </div>
         
              
    </div>
              
     


    <div class="col-md-8">

      <div style="color: grey; background: lightgrey; height: 550px" class="jumbotron">


        <table style="border: 3px solid #FAF4F4"class = "table">

        	<%= render 'form' %>


        
        </table>

        


      </div>

      <!-- Indicates caution should be taken with this action -->

    </div>

      
   </div>



</div>



<div>

concertReview/app/views/concerts/show.html.erb
<div class="container">


  <div style="background-color: white" class="container">


    <h1 style="font-family: sans-serif;
color: grey;"> Concert Created </h1>





    <div class="row">



    <div class="col-md-4">

      <div style="color: grey;background: lightgrey; height: 400px" class="jumbotron">

      <table style="border: 3px solid #FAF4F4"class = "table">


      <p>
        <strong>Reviews:</strong>

        <% @concert.reviews.each do |review| %>
          <div>
            <b>Overall rating: <%= review.overallRating %></b> &nbsp
            <b>Comments: <%= review.comments %></b>
            <b style="color:lightcoral"><%= link_to 'Read More', review %></b>
          </div>
        <% end %>
      </p>
    </table>


   

    </div>
         
              
    </div>
              
     


    <div class="col-md-8">

      <div style="color: grey; background: lightgrey; height: 400px" class="jumbotron">


        <table style="border: 3px solid #FAF4F4"class = "table">


        <p style="font-size: 20px !important">
          <strong>Artist:</strong>
          <%= link_to @concert.artist.name, @concert.artist %>
        </p>

        <p>
          <strong>Venue:</strong>
          <%= @concert.venue %>
        </p>

        <p>
          <strong>Date:</strong>
          <%= @concert.date %>
        </p>

        <p>
          <strong>Average Overall Rating:</strong>
          <%= @concert.averageOverall %>
        </p>



        <p>
          <strong>Average Song Selection Rating:</strong>
          <%= @concert.averageSongSelection %>
        </p>

        <p>
          <strong>Average Stage Presence Rating:</strong>
          <%= @concert.averageStagePresence %>
        </p>


        <button style="float: right" type="button" class="btn btn-warning"> <%= link_to 'Back', concerts_path %></button>

      </table>

        


      </div>

      <!-- Indicates caution should be taken with this action -->

    </div>

      
   </div>



</div>



<div>










<!--

<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= link_to @concert.artist.name, @concert.artist %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @concert.venue %>
</p>

<p>
  <strong>Date:</strong>
  <%= @concert.date %>
</p>

<p>
  <strong>Average Overall Rating:</strong>
  <%= @concert.averageOverall %>
</p>



<p>
  <strong>Average Song Selection Rating:</strong>
  <%= @concert.averageSongSelection %>
</p>

<p>
  <strong>Average Stage Presence Rating:</strong>
  <%= @concert.averageStagePresence %>
</p>

<p>
	<strong>Reviews:</strong>

	<% @concert.reviews.each do |review| %>
		<div style="border:1px solid black; border-radius: 5px";>
			<b>Overall rating: <%= review.overallRating %></b> &nbsp
			<b>Comments: <%= review.comments %></b>
			<b><%= link_to 'Read More', review %></b>
		</div>
	<% end %>
</p>



<%= link_to 'Back', concerts_path %>
-->