concertReview/config/routes.rb
ConcertReview::Application.routes.draw do
  resources :concerts, except: [:new, :edit, :delete]
  resources :artists, except: [:new, :edit, :delete]
  resources :reviews, except: [:edit, :delete]

  get "sessions/new"
  get "users/new"  
  resources :users
  resources :sessions

  get "review/index"
  get "review/artist"
  get "review/date"
  get "review/venue"
  get "review/genre"
  get "review/comments"

  root 'reviews#home'

  get 'reviews/' => 'reviews#home'
  get 'concerts/' => 'concert#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "account" => "sessions#account", :as => "account"
  

end

concertReview/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  helper_method :recentReviews

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  def recentReviews
    @recentReviews = Review.last(10).reverse
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create

    date_string = "#{review_params['date(1i)']}-#{review_params['date(2i)']}-#{review_params['date(3i)']}"
    #review_params[:artist].capitalize!
    #review_params[:venue].capitalize!
    artist_string = review_params[:artist].titleize
    venue_string = review_params[:venue].titleize
    #only works for creating the concert/artist, review still has lowercase

    @review = Review.create(review_params)

    if @review.save
      @artist = Artist.find_or_create_by(name: artist_string)
      @concert = Concert.find_or_create_by(artist: @artist, venue: venue_string, date: date_string)
      @review.concert_id = @concert.id
      @review.user_id = session[:user_id]
      @review.save
    end

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:artist, :venue, :date, :genre, :sound, :stagePresence, :songSelection, :overallRating, :comments)
    end
end

concertReview/app/helpers/review_helper.rb
module ReviewHelper
end

concertReview/app/helpers/reviews_helper.rb
module ReviewsHelper
end

concertReview/app/views/reviews/_form.html.erb
<%= javascript_include_tag 'jquery.raty' %>
<%= stylesheet_link_tag "custom", media: "all" %>

<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<!--
<div id="stars"></div>
-->

  <div class="form-control:focus">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :venue %>
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :date %>
    <%= f.date_select(:date, :start_year => 1990) %>
  </div>
  <div class="field">
    <%= f.label :genre %>
    <%= f.select :genre, [['Rock','Rock'],['Pop','Pop'],['Electronic','Electronic'],['Country','Country'],['Hip Hop','Hip Hop'],['Folk','Folk'],['Jazz','Jazz'], ['Other', 'Other']] %>
  </div>
  <div class="field">
    <%= f.label :sound %>
    <%= f.select :sound, (1..5) %>
  </div>
  <div class="field">
    <%= f.label "Stage Presence" %>
    <%= f.select :stagePresence, (1..5) %>
  </div>
  <div id="field">
    <%= f.label "Song Selection" %>
    <%= f.select :songSelection, (1..5) %>
  </div>
  <div class="field">
    <%= f.label "Overall Experience" %>
    <%= f.select :overallRating, (1..5) %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments, :size => "50x10"%>
  </div>
 
         <%= f.submit %></button>
  
<% end %>

concertReview/app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

concertReview/app/views/reviews/home.html.erb
<%= javascript_include_tag 'jquery.raty' %>
<!--
<img src="http://www.mcd.ie/oasis_slane2009/Slane_2009.jpg">
-->

<html>
  <head>
  <link href='http://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'> 
      <%= stylesheet_link_tag "custom", media: "all" %>
  </head>


  <body>





    
      <div class="container" style="background: lightgrey">


       

      <div style="background: #999; margin-right: 25px; margin-left: 25px ;margin: 0px;border: grey"class="panel panel-default">

         <div class="panel-body">
            <h2   align="center" style="font-size: 40px;width: 100%; color: white; margin-top: -4px; margin-bottom: -4px; font-family: 'Oswald', sans-serif">  ConcertReview.com </h2>
         </div>
      </div>



        <div class="row">

            
             <div style="border: 3px solid #FAF4F4" id="myCarousel" class="carousel slide">
                  
                  <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                  </ol>

                  
                  <!-- Carousel items -->
                  <div class="carousel-inner">
                        <div class="item active">
                              <img style="margin: 0 auto;width: 100%;height:500px"src = "http://thelantern.com/wp-content/uploads/2014/04/IMG_5460-1024x682.jpg" alt="Show" >
                              <div class="carousel-caption">
                                <h3>DAvid Guetta</h3>
                                <p> Margharet River Live</p>
                              </div>          
                        </div>

                        <div class="item">
                          <img style="margin: 0 auto; width: 100%; height: 500px" src = "http://www.aceshowbiz.com/images/wennpic/david-guetta-free-concert-10.jpg" alt="Concer" >
                            <div class="carousel-caption">
                              <h3> Bonobo </h3>                        
                              <p> Germany Sessions</p>
                            </div>
                        </div>

                          <div class="item">
                          <img style="margin: 0 auto; width: 100% ; height: 500px" src = "http://www.scenicreflections.com/files/Concert%20Wallpaper__yvt2.jpg" alt="Live" >
                            <div class="carousel-caption">
                              <h3> Jon JOn</h3> 
                              <p> Pop world</p>
                            </div> 
                          </div>
        <!-- inner carousel ends -->                  
                    </div>
        <!-- Carousel nav begins -->
                  <a class="carousel-control left" href="#myCarousel" data-slide="prev"><span class= "icon-prev"></span>
                  </a>
                  <a class="carousel-control right" href="#myCarousel" data-slide="next"><span class= "icon-next"></span>
                  </a>
        <!-- my carousel ends -->
            </div>
        <!-- container ends -->
         
        </div>
      <br>
      <br>
      <br>

    <% if current_user %>
    <% user = User.find(session[:user_id]) %>
    <% end %>



    
      <!-- Example row of columns -->
      <div class="row">
        <div style="border: 3px solid #FAF4F4" class="col-md-4">
          <h1>Follow your band</h1>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/jumbotron/#" role="button">View details »</a></p>
        </div>
        <div style="border-top: 3px solid #FAF4F4;border-bottom: 3px solid #FAF4F4;border-left: 1.5px solid #FAF4F4;border-right: 1.5px solid #FAF4F4"  class="col-md-4">
          <h1>Know before you go</h1>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/jumbotron/#" role="button">View details »</a></p>
       </div>
        <div style="border: 3px solid #FAF4F4" class="col-md-4">
          <h1>Most reviewed</h1>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/jumbotron/#" role="button">View details »</a></p>
        </div>
      </div>

     

      <br>
      <br>
      <br>
      <br>



  <div style="background: #999; border: grey"class="panel panel-default">
       <div class="panel-body">
          <h2   align="center" style="font-size: 40px; color: white; margin-top: -4px; margin-bottom: -4px; font-family: 'Oswald', sans-serif">  Features </h2>
       </div>
    </div>



  

    <div class = "row">


          <div class = "col-12 col-md-4" style="border:5px solid white; border-radius: 5px;">
            <h1>Upcoming Events Near You</h1>
            <!-- need to look into moving remote somewhere else and making it site wide -->
            <% remote = Songkickr::Remote.new 'WrlX22JJAxW2489I' %>

              <% @sf = remote.metro_areas_events('26330', :per_page => '5').results %>
                <% @sf.each do |event| %>
                <p><%= link_to event.display_name, event.uri, :target => "_blank"%></p> <!-- need to ask about why tickets_uri doesn't work --> 
              <% end %>
      
          </div>

          <div class = "col-12 col-md-4" style="border:5px solid white; border-radius: 5px;">
              <h1>Recent Reviews</h1>
             
                <% @recentReviews = Review.limit(3).order('id DESC') %>
                <% @recentReviews.each do |review| %>
                 <div style="border:3px solid white; border-radius: 5px";>
                      <p><b>Artist:</b> <%= link_to review.concert.artist.name, review.concert.artist %> &nbsp
                      <b>Venue:</b> <%= review.venue %> &nbsp
                      <b>Date:</b> <%= review.date %> &nbsp
                      <b>Overall Rating:</b> <%= review.overallRating %></p>
                      <p><b>Comments:</b> <%= review.comments %></p>

                       <%= link_to 'Read Full Review', review %> 
                    <% if (review.concert.reviews.size > 1)%>
                      <br><%= link_to "Read all #{review.concert.reviews.size} Reviews From This Concert", review.concert %>
                    <% end %>
                </div>
                  
                   <% end %>
            </div>
        
          

          <div class = "col-12 col-md-4" style="border:5px solid white; border-radius: 5px;">
            <div id = 'Popular Concerts'>

              <h1>Popular Concerts</h1>

              <% @concerts = Concert.all.sort_by{|concert| concert.reviews.size}.last(5).reverse %>
              <% @concerts.each do |concert| %>
                <% if(concert.reviews.size > 1) %>
                    <div style="border:1px solid white; border-radius: 5px";>
                    <p><b>Artist:</b> <%= concert.artist.name %> &nbsp
                    <b>Venue:</b> <%= concert.venue %> &nbsp
                    <b>Average Overall Rating:</b> <%= concert.averageOverall %> &nbsp
                    <b>Date:</b> <%= concert.date %> &nbsp <br>
                    <%= link_to "#{concert.reviews.size} Reviews", concert %>
                    </div>
                <% end %>
             </div>

           <% end %>

         </div>

        </div>




          












    
</div>























  
   

   

        <script> src="//ajax.gooleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"
        </script>
        <script>window.jQuery || document.write('<script src= "../assets/javascripts/bootstrap.js"><\/script>')</script>
          
          <script>
          $(document).ready(function(){
            $('carousel').carousel();
          });
          </script>


        
</body>
</html>
<!--
          <div class = "col-12 col-md-3" style="border:1px solid black; border-radius: 5px;">
            <h1>Upcoming Events Near You</h1>
            <!-- need to look into moving remote somewhere else and making it site wide --
                <% if current_user %>
                  <% remote = Songkickr::Remote.new 'WrlX22JJAxW2489I' %>
                  <% @loc = remote.location_search(user.location).results.first %>
                  <% @shows = remote.metro_areas_events(@loc.metro_area.id, :per_page => '10').results %>
                    <% @shows.each do |event| %>
                    <p><%= link_to event.display_name, event.uri, :target => "_blank"%></p> <!-- need to ask about why tickets_uri doesn't work -- 
                <% end %>
                 <% else %>
                  <p><%= link_to "Log in to see upcoming shows in your area!", log_in_path %></p>
                  <% end %>
          </div>


-->

concertReview/app/views/reviews/index.html.erb
<%= javascript_include_tag 'jquery.raty' %>

<html>
  <head>
  <link href='http://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'> 
      <%= stylesheet_link_tag "custom", media: "all" %>
  </head>



  <body>
      
     
         


      <div class="container">



            <div class="panel panel-default">
             <div class="panel-body">
                <h2   align="center" style="font-size: 40px; margin-top: -4px; margin-bottom: -4px; font-family: 'Oswald', sans-serif">  Recent Reviews </h2>
             </div>
            </div>

      <!--

 <tr>
                <% @recentReviews = Review.limit(3).order('id DESC') %>
                <% @recentReviews.each do |review| %>
                 
                      <p><b>Artist:</b> <%= link_to review.concert.artist.name, review.concert.artist %> &nbsp
                      <b>Venue:</b> <%= review.venue %> &nbsp
                      <b>Date:</b> <%= review.date %> &nbsp
                      <b>Overall Rating:</b> <%= review.overallRating %></p>
                      <p><b>Comments:</b> <%= review.comments %></p>

                       <%= link_to 'Read Full Review', review %> 
                       <% if (review.concert.reviews.size > 1)%>
                      <br><%= link_to "Read all #{review.concert.reviews.size} Reviews From This Concert", review.concert %>
                    <% end %>
                  <% end %>
              </tr>





     -->

            

                
            


          <div class="col-md-4">

      <div style=" border: 3px solid #FAF4F4;background: lightgrey; height: 500px" class="jumbotron">
       
               <h2  style="color: grey;font-size: 30px; font-family: 'Oswald', sans-serif">  What do you say? </h2>


          <div style="border: 3px solid #FAF4F4"class="list-group">
            
            <a  style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Check out Artists</a>
            <a style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Write your Review!</a>
            <a style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Follow Your Band!</a>
            <a style="font-size: 18px; font-family: 'Oswald', sans-serif"href="#" class="list-group-item">Upcoming Concerts</a>
          </div>
              
        </div>
    </div>


    <div class="col-md-8">

      <div style="border: 3px solid #FAF4F4;background: grey; height: 500px" class="jumbotron">

               <h2  style="color: white;font-size: 30px; font-family: 'Oswald', sans-serif">  Recent Reviews </h2>

                <table style="border: 3px solid #FAF4F4"class = "table">
                
                <tr>
                  <th><%= sortable "artist", "Artist" %></th>
                  <th><%= sortable "venue", "Venue" %></th>
                  <th><%= sortable "date", "Date" %></th>
                  <th><%= sortable "numReviews", "Reviews" %></th>
                  <th><%= sortable "avgRating", "Average Overall Rating" %></th>
                  <th>All Reviews & Ratings</th>
                </tr>

                <% @reviews.each do |review| %>

                <tr>
                  <td><%= link_to "#{review.artist}", review.artist %></td>
                  <td><%= "#{review.venue}" %></td>
                  <td><%= "#{review.date}" %></td>
                  <td><%= "#{review.overallRating}" %></td>
                  <td><%= "#{review.overallRating}" %></td>
                  <td><%= link_to "Read More", review %></td>
                </tr>

                <% end %>

                </table>

          </div>
      </div>

     


        <div class="row">

          <div style="border: 3px solid #FAF4F4"class="col-md-4">
            <h1>follow your band</h1>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-default" href="http://getbootstrap.com/examples/jumbotron/#" role="button">View details »</a></p>
          </div>

          <div style="border-top: 3px solid #FAF4F4;border-bottom: 3px solid #FAF4F4;border-left: 1.5px solid #FAF4F4;border-right: 1.5px solid #FAF4F4" class="col-md-4">
            <h1>know before you go</h1>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-default" href="http://getbootstrap.com/examples/jumbotron/#" role="button">View details »</a></p>
         </div>
          <div style="border: 3px solid #FAF4F4" class="col-md-4">
            <h1>most reviewed</h1>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-default" href="http://getbootstrap.com/examples/jumbotron/#" role="button">View details »</a></p>
          </div>

        </div>

      </div>




            
             
      
      

   

        <script> src="//ajax.gooleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"
          </script>
          <script>window.jQuery || document.write('<script src= "../assets/javascripts/bootstrap.js"><\/script>')</script>
            
            <script>
            $(document).ready(function(){
              $('carousel').carousel();
            });
          </script>

     


        
</body>
</html>

concertReview/app/views/reviews/new.html.erb
<!-- concert new view -->

<div class="container">


  <div style="background-color: white" class="container">


    <h1 style="font-family: sans-serif;
    color: grey;"> New Concert</h1>





    <div class="row">



    <div class="col-md-4">

      <div style="color: grey;background: lightgrey; height: 550px" class="jumbotron">

      <table style="border: 3px solid #FAF4F4"class = "table">


      <p>
        <strong>Tell us about it...</strong>

        
      </p>
    </table>


   

    </div>
         
              
    </div>
              
     


    <div class="col-md-8">

      <div style="color: grey; background: lightgrey; height: 550px" class="jumbotron">


        

        	<%= render 'form' %>


        
        

        


      </div>

      <!-- Indicates caution should be taken with this action -->

    </div>

      
   </div>



</div>



<div>

concertReview/app/views/reviews/show.html.erb
<html>

<body>

  <div class="container">

    <div class="panel panel-default">
       <div class="panel-body">
          <h2   align="center" style="font-size: 40px; margin-top: -4px; margin-bottom: -4px">  Cheers !!</h2>
       </div>
    </div>

    
    <div class="row">


      <p id="notice"><%= notice %></p>

          <div class="col-md-8">

            <div style="background: grey; height: 500px" class="jumbotron">

             <h1 style="font-size:85px"><%= link_to "#{@review.artist} live at #{@review.venue}                                                                          

             ", @review.concert %></h1>



           </div>

          </div>
<!--
<p>
  on #{@review.date}
  <strong>Artist:</strong>
  <%= @review.artist %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @review.venue %>
</p>

<p>
  <strong>Date:</strong>
  <%= @review.date %>
</p>

--> 

   <div class="col-md-4">

    <div style="background: grey; height: 500px" class="jumbotron">
          <p>
            <strong>Genre:</strong>
            <%= @review.genre %>
          </p>

          <p>
            <strong>Sound:</strong>
            <%= @review.sound %>
          </p>

          <p>
            <strong>Stage Presence:</strong>
            <%= @review.stagePresence %>
          </p>

          <p>
            <strong>Song Selection:</strong>
            <%= @review.songSelection %>
          </p>

          <p>
            <strong>Overall Rating:</strong>
            <%= @review.overallRating %>
          </p>

          <p>
            <strong>Review:</strong>
            <%= @review.comments %>
          </p>

          <% if (@review.concert.reviews.size > 1)%>
            <%= link_to "Read all #{@review.concert.reviews.size} Reviews From This Concert", @review.concert %> <br>
          <% end %>

          <button type="submit" class="btn btn-primary">
          <%= link_to 'Back', reviews_path %>
          </button>
          
        </div>
    </div>


   </div>


  </div>

</body>
</html>